#Use an official Node runtime as a parent image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

COPY .env .env

# Expose the port the app runs on
EXPOSE 5050

# Define the command to run the apps
CMD ["node", "index.js"]